### ISSUE TITLE
Overlay Header Overlaps With Mobile Navigation

### ISSUE THREAD

**Issue by wlin702** [Obox/layerswp#43] opened 2015-03-16 03:37 UTC
## Description of issue
In mobile view, header moves to the left when you click on the navigation menu from the top of the page. But once you scroll down and utilize the overlay header, the header doesn't move and stays in place.

## URL of page exhibiting the issue
http://bit.ly/1MDQ06O

## Web Browser(s) that exhibit the issue
Google Chrome
Safari
Internet Explorer

## Error Message or Steps to Recreate
Scroll page down until overlay header appears, click on navigation menu. Happens on desktop browser, mobile browser & responsinator.

**Comment by vailjoy** [comment] 2015-03-19 14:17
Hi there,
I am unable to recreate in the current version so this should be fixed with 1.0.5

**Comment by davidperel** [comment] 2015-03-20 11:02
Hi wlin702

This may only happen if you're resizing the browser window. If a user visits your site on mobile they wont experience the bug.

**Comment by wlin702** [comment] 2015-03-20 17:37
Hey davidperel- I've tried it on my phone already on both Chrome and Safari. Same issue.

**Comment by davidperel** [comment] 2015-03-23 13:18
Ok, we will do some more thorough testing on some devices at the office and
get back to you with a fix.

On Fri, Mar 20, 2015 at 7:37 PM, wlin702 <notifications@github.com> wrote:

> Hey davidperel- I've tried it on my phone already on both Chrome and
> Safari. Same issue.
>
>
>
> > On Mar 20, 2015, at 4:02 AM, davidperel <notifications@github.com>
> wrote:
> >
> > Hi wlin702
> >
> > This may only happen if you're resizing the browser window. If a user
> visits your site on mobile they wont experience the bug.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Obox/layerswp/issues/43#issuecomment-84083239>.
>



-- 
Regards

David Perel
Co-founder, Obox

Twitter <http://twitter.com/obox>

**Comment by AndreasWebdev** [comment] 2015-03-24 10:54
Samsung Galaxy S4 /w Android 5.0
I can confirm this bug!
Screenshot: 
![screenshot 24 03 2015 11-53-22](https://cloud.githubusercontent.com/assets/7365286/6800184/809f14e2-d21c-11e4-91dd-0ee672eaa62b.png)

**Comment by flowgrow** [comment] 2015-04-13 16:28
definitely still an issue!
key to experiencing this bug is **scrolling down**
when you are on top of the page, everything is looking fine, and the menu gets pushed to the side
but when scrolled down, it won't get pushed to the side anymore.

this means, that the problem is probably related to sticky-kit

**Closed** 2015-05-04 13:47 UTC
Labels: bug
