### ISSUE TITLE
Menu Position is not changing

### ISSUE THREAD

**Issue by creativeer** [Obox/layerswp#131] opened 2015-05-16 11:14 UTC
Hi,

i use your Plugin since the Beginning and it is good Way to Start building Websites. But there are some glitches that needs to be fixed.

The first is:
If i start a new Build from Scratch, the Pages are visible in the right Header Menu Area by Default. If i build a new Menu with my custom Order and Pages to include, the default Menu goes not away. It is in his Place.

I have made two Screenshots, to show you what i mean. In the first, you can see, the default pages that Layers makes. The 2nd is the Menu (Mainmenu) that i have made. You can see the default Menu isn't going away.

Wordpress is newest Version. Layers also and no fancy Plugins.

Is this a Bug?

![screenshot-default-menu](https://cloud.githubusercontent.com/assets/2089316/7665897/cdaf30da-fbcc-11e4-9dee-78cb50af76c1.png)
![screenshot-mainmenu](https://cloud.githubusercontent.com/assets/2089316/7665898/d87011ce-fbcc-11e4-88db-d635af51ec05.png)

**Comment by vailjoy** [comment] 2015-05-19 13:19
Hi there,
Layers has several menu locations which you can see on the Appearance > Menus screen when editing or creating a menu, or in the Customizer under the Navigation section. The dark bar on top currently has a menu set in the Top Right menu location. To get it to go away, go to Layers > Customize, expand Navigation, and set the top menu drop-downs to ------- for blank, then ensure the Header Menu has the menu you want selected.

**Comment by creativeer** [comment] 2015-05-21 08:57
Hi vail,

sorry you don't understand me. In the Moment i create Pages, Layers show this Pages as Menu in the right place. Now i want this Dropdown Menu with my own Pages. I go to the Menus Section and create a new menu. But now comes the Bug, if i want my own menu in the place, this default menu goes not away. Even if i make the dropdown to blank. I have made an another Screenshot with more Pages and Subpages to show you what i mean.

On your Support Website, there is this problem also in the discussion,
look here:
http://docs.layerswp.com/help/question/9871/how-do-i-remove-a-menu-from-any-area/

So please look more accurate at this Issue, because it is really a showstopper to build a new website with your system.

thank you.

![screenshot-menu-position](https://cloud.githubusercontent.com/assets/2089316/7745004/32d95470-ffa8-11e4-974b-4308499049ab.jpg)

**Comment by marcperel** [comment] 2015-05-21 10:36
Thanks for pointing this out, we default the menu to list your pages so that you can navigate around your site before you've set a menu. It's common practice on themes to do this. The easiest way to fix the problem is to create a blank menu in Appearance > Menus and assign that menu to your menu.

~ Marc

**Comment by creativeer** [comment] 2015-05-21 14:07
Hey Marc,

sorry, but this is not the solution. In one of the older Versions of Layers, it was no problem to set my own menu at the right place. the default pages menu what you mean was going away and the new menu with the dropdown was in this place. Now this default pages menu isn't going away, even if i make a new menu and try to set this new menu in this place.

i was following your advice and have made a "blank" menu with no pages in it. and bang, look at this screenshot, the default pages menu is there?!

what should i do, going back to layers version 1.0?

![screenshot-default-menu](https://cloud.githubusercontent.com/assets/2089316/7750250/6ab8e6b4-ffd3-11e4-8aac-3a6edb511672.jpg)

**Comment by marcperel** [comment] 2015-05-21 14:11
Thanks for the description, we'll take your feedback and find a solution which doesn't involve you changing versions :)

**Comment by creativeer** [comment] 2015-05-21 14:27
Thanks for your fast response marc. I can also give you more infos if this helps.

**Comment by marcperel** [comment] 2015-05-25 15:03
I've created a blank menu and assigned it to the **Header Menu** and I have no menu showing on the front end.

https://www.dropbox.com/s/h5dm6ca5162dxd7/Screenshot%202015-05-25%2017.02.42.png?dl=0

If you do the same, does it still spit pages out for you? I'm on WordPress 4.2.2

**Comment by creativeer** [comment] 2015-05-26 07:47
Yes that seems to work also here. In the Header Menu Position, i have the correct Menu Layout, even with these Drop Down hover. Strange, because on the other Positions the Bug appear. Is it maybe a Javascript Thingy somewhere?

**Comment by marcperel** [comment] 2015-05-26 08:04
I'll test the other positions with blank menus and see what comes up.

**Comment by creativeer** [comment] 2015-06-01 14:05
Hey Marc,

you have closed this Issue. Have you found a Solution?

**Comment by marcperel** [comment] 2015-06-01 14:11
Sorry, was closed in error

**Comment by vailjoy** [comment] 2015-07-03 11:07
Hi there,
What this boils down to is that you need to have a header menu. If you don't, WordPress will load the fallback menu, which we cannot remove because - it is a fallback. In most cases, this fallback loads 2 links on a new site - Home and Sample Page, and does not display the poor formatting (which is a result of having too many top-level links for the header layout you are using). If the setup guide is followed, a custom header menu will be created. If you don't want any links at all, then it is left blank. We cannot account for customization choices with code - we can only offer the freedom for those choices to take place. Hope that makes sense.

**Closed by vailjoy** 2015-07-03 11:07 UTC
Labels: bug

**Comment by creativeer** [comment] 2015-07-16 12:12
Hi,

no that makes no sense. You have closed this Issue but you dont understand what i was meaning. This poor Formatting was the Result of the non functional placement of your Menu Position Feature. That it was working was made clear on one of the posts above ("Yes that seems to work also here. In the Header Menu Position, i have the correct Menu Layout, even with these Drop Down hover. Strange, because on the other Positions the Bug appear. Is it maybe a Javascript Thingy somewhere?"). After that, there was no clear solution from you. Just standard Answers that i read from you....

Sorry Vailjoy for that wording, but i had so much trouble with this plugin since the beginning, that i cant accept your answers, that are not a solution to the problem.
